title: "Irish Debbarma"
author: "Irish Debbarma"
description: "Indian Institute of Science"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home", icon: home}
  - {file: "README.md", title: "About me"}
  - {file: "blogposts.md", title: "Blog", icon: book}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:irishdb29@gmail.com"}
  - {title: Github, icon: github, url: "https://debbarma2000.github.io"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/irishdebbarma"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
